#
###################################
# Site wide configuration
####################################
#
title: it me wario
email:
description: A simple and awesome blog theme powered by jekyll.
url: # the base hostname & protocol for your site
keywords: ["blog", "jekyll"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Paris
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Christopher Huong
  avatar: meee.png
  job: "point guard for the kentucky fried chickens"
  bio: "Numerous ionotropic glutamate receptor subunits are expressed by heart tissue, but their specific function is still unknown. Western blots and northern blots confirmed the presence of iGluRs in cardiac tissue. Immunohistochemistry localized the iGluRs to cardiac nerve terminals, ganglia, conducting fibers, and some myocardiocytes.[27] Glutamate receptors are (as mentioned above) also expressed in pancreatic islet cells."
  email: chrishuong95@gmail.com
  disqus-shortname:
  twitter: huongtopher
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: huongtopher
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: chris-h-1685951a1
  skype: #username
  xing: #username
  instagram: topherhuong
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: #username
